services:
  neo4j:
    image: neo4j:5-community
    container_name: ir-neo4j-dev
    ports:
      - "7474:7474"   # HTTP UI
      - "7687:7687"   # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: ir-api-dev
    environment:
      - PORT=4000
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      # Entra placeholders (configure for real auth later)
      - AUTH_ISSUER=https://login.microsoftonline.com/<tenant-id>/v2.0
      - AUTH_AUDIENCE=api://<application-id-or-uri>
      - ROLE_GROUP_VIEWER=<group-object-id>
      - ROLE_GROUP_EDITOR=<group-object-id>
      - ROLE_GROUP_ADMIN=<group-object-id>
      - NODE_ENV=development
    ports:
      - "4000:4000"
    depends_on:
      - neo4j
    volumes:
      - .:/workspace
      - /workspace/node_modules
    working_dir: /workspace/api
    command: ["sh", "-c", "npm install && npm run dev"]
volumes:
  neo4j-data: {}
  neo4j-logs: {}
